### ISSUE TITLE
Configurar entorno con Vite y GitHub Actions

### ISSUE THREAD

**Issue by dangarbar** [dangarbar/portfolio-vue3#1]
Inicializar el proyecto con Vite y configurar GitHub Actions para CI/CD.

**Comment by dangarbar** [comment]
# 🚀 Configurar entorno con Vite y GitHub Actions para Vue 3

## 📌 Objetivo  
Inicializar un proyecto en **Vue 3** utilizando **Vite** y configurar **GitHub Actions** para la automatización del despliegue en Netlify.

---

## 🔹 Pasos para completar la tarea  

### 1️⃣ Crear el proyecto con Vite  
Ejecuta el siguiente comando para generar la estructura del proyecto con Vue 3 y Vite:

```bash
npm create vite@latest portfolio-vue3 --template vue
```

📌 **Opciones a seleccionar:**  
- **Project Name**: `portfolio-vue3`  
- **Framework**: `Vue`  
- **Variant**: `JavaScript` o `TypeScript` según prefieras.  

Accede a la carpeta del proyecto e instala las dependencias:  

```bash
cd portfolio-vue3
npm install
```

Para probar el proyecto en el navegador, usa:  

```bash
npm run dev
```

Esto abrirá la aplicación en `http://localhost:5173/`.

---

### 2️⃣ Configurar el repositorio en GitHub  
Inicializa un repositorio Git y sube el código a GitHub:  

```bash
git init
git add .
git commit -m "🚀 Configuración inicial del proyecto Vue 3 con Vite"
git branch -M main
git remote add origin https://github.com/dangarbar/portfolio-vue3.git
git push -u origin main
```

Verifica el repositorio en:  
🔗 [https://github.com/dangarbar/portfolio-vue3](https://github.com/dangarbar/portfolio-vue3)

---

### 3️⃣ Configurar GitHub Actions para CI/CD  
📌 **Objetivo:** Crear un workflow que compile el proyecto y lo despliegue en **Netlify**.

Crea la carpeta de workflows:  

```bash
mkdir -p .github/workflows
```

Crea el archivo de workflow en `.github/workflows/deploy.yml`:  

```yaml
name: Deploy Vue 3 App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout del código
        uses: actions/checkout@v3

      - name: 🔧 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🏗 Construir la aplicación
        run: npm run build

      - name: 🚀 Desplegar en Netlify
        run: npx netlify deploy --prod --auth=${{ secrets.NETLIFY_AUTH_TOKEN }}
```

---

### 4️⃣ Configurar el Token de Netlify en GitHub  
1. Accede a [Netlify Access Tokens](https://app.netlify.com/user/applications) y genera un nuevo token.  
2. En GitHub, ve a **Settings → Secrets and variables → Actions → New repository secret**.  
3. Crea una variable llamada **`NETLIFY_AUTH_TOKEN`** y pega el token generado.  

---

### 5️⃣ Subir cambios y probar el workflow  
Confirma los cambios y súbelos a GitHub:  

```bash
git add .
git commit -m "🚀 Configuración de Vue 3 y GitHub Actions para Netlify"
git push origin main
```

Esto activará automáticamente el workflow en **GitHub Actions** y desplegará la aplicación en **Netlify**.

---

## 📌 Criterios de finalización de la tarea  
✅ **El proyecto Vue 3 con Vite está inicializado y funcionando correctamente.**  
✅ **El código está subido al repositorio en GitHub.**  
✅ **El workflow de GitHub Actions está configurado correctamente.**  
✅ **Netlify despliega automáticamente la aplicación.**  
✅ **Los cambios están organizados y siguen buenas prácticas.**
