### ISSUE TITLE
Configurar despliegue en Netlify con GitHub Actions

### ISSUE THREAD

**Issue by dangarbar** [dangarbar/portfolio-vue3#7]
Automatizar el despliegue de la aplicación en Netlify mediante GitHub Actions.

**Comment by dangarbar** [comment]
# 🚀 Configurar despliegue en Netlify con GitHub Actions

## 📌 Objetivo  
Automatizar el despliegue de la aplicación Vue 3 en **Netlify** utilizando **GitHub Actions**.

---

## 🔹 Pasos para completar la tarea  

### 1️⃣ Instalar la CLI de Netlify  
Ejecuta el siguiente comando para instalar la CLI de Netlify en tu máquina local:  

```bash
npm install -g netlify-cli
```

Inicia sesión en Netlify:  

```bash
netlify login
```

---

### 2️⃣ Configurar Netlify en el proyecto  
Ejecuta el siguiente comando para inicializar Netlify en el proyecto:

```bash
netlify init
```

📌 **Opciones a seleccionar:**  
1. **"Create & configure a new site"** si no tienes un sitio en Netlify.  
2. Selecciona la cuenta de Netlify.  
3. Define `dist/` como el directorio de salida.  
4. Usa los valores predeterminados para los demás ajustes.  

Esto generará un archivo `netlify.toml` en la raíz del proyecto.

---

### 3️⃣ Configurar el Token de Netlify en GitHub  
1. Accede a [Netlify Access Tokens](https://app.netlify.com/user/applications) y genera un nuevo token.  
2. En GitHub, ve a **Settings → Secrets and variables → Actions → New repository secret**.  
3. Crea una variable llamada **`NETLIFY_AUTH_TOKEN`** y pega el token generado.  

---

### 4️⃣ Crear el workflow de GitHub Actions  
Crea la carpeta de workflows en el proyecto:  

```bash
mkdir -p .github/workflows
```

Crea el archivo `.github/workflows/deploy.yml`:  

```bash
touch .github/workflows/deploy.yml
```

Agrega la siguiente configuración en `deploy.yml`:  

```yaml
name: Deploy Vue 3 App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout del código
        uses: actions/checkout@v3

      - name: 🔧 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🏗 Construir la aplicación
        run: npm run build

      - name: 🚀 Desplegar en Netlify
        run: npx netlify deploy --prod --auth=${{ secrets.NETLIFY_AUTH_TOKEN }}
```

---

### 5️⃣ Subir cambios y probar el workflow  
Confirma los cambios y súbelos a GitHub:  

```bash
git add .
git commit -m "🚀 Configuración de despliegue automático en Netlify"
git push origin main
```

📌 Esto activará automáticamente el workflow en **GitHub Actions** y desplegará la aplicación en **Netlify**.

---

## 📌 Criterios de finalización de la tarea  
✅ **Netlify Hosting está configurado en el proyecto.**  
✅ **El token de Netlify está almacenado en GitHub Secrets.**  
✅ **El workflow de GitHub Actions automatiza el despliegue en Netlify.**  
✅ **Un push a `main` activa el despliegue automáticamente.**  
✅ **Los cambios están subidos al repositorio en GitHub.**
